riffusion/riffusion

README.md

Add quotes and remove trailing commas.

Make the example input and output valid JSON strings

---

riffusion/audio.py

Hey guys! I gave an image_to_spectrogram implementation a go of it, seems to work from what I can tell. Implemented this to allow for style transfer on custom-uploaded audio :)
closes: #9

Add image_from_spectrogram to audio.py

---

integrations/baseten.py
pyproject.toml
riffusion/cli.py
riffusion/datatypes.py
riffusion/riffusion_pipeline.py
riffusion/server.py
riffusion/spectrogram_converter.py
riffusion/spectrogram_image_converter.py
riffusion/spectrogram_params.py
test/image_util_test.py
test/linter_test.py
test/spectrogram_image_converter_test.py
test/test_case.py

Enable ruff import sorting

---

.github/workflows/ci.yml
requirements.txt

Add CI with github actions

---

README.md
pyproject.toml

Add detail to readme

---

README.md
riffusion/server.py
riffusion/spectrogram_converter.py
riffusion/util/audio_util.py

Disable compression by default, too slow

---

riffusion/streamlit/pages/interpolation.py

Topic: playground_improvements

Improve interpolation playground

---

riffusion/util/image_util.py

Closes: #51
Topic: convert_three_channel

Convert to three-channel if needed in spectrogram_from_image

---

riffusion/spectrogram_params.py

Closes: #30
Topic: params_docs

Add note to SpectrogramParams about torchaudio docs

---

riffusion/audio_splitter.py
riffusion/streamlit/pages/sample_clips.py
riffusion/streamlit/pages/split_audio.py
riffusion/streamlit/playground.py
riffusion/streamlit/util.py
riffusion/util/audio_util.py

Audio splitter

---

riffusion/streamlit/pages/interpolation.py

Rename interpolation page

---

cog.yaml
integrations/README.md
integrations/cog_riffusion.py
riffusion/riffusion_pipeline.py

@hmartiro here's my take on pulling out those redundant load functions. Didn't have permissions to push to your branch (I'm sensing a pattern here 😄), so here's a PR to make said changes to it. Lmk what you think.

cog using common load fxn

---

.github/workflows/playground-update.yml

Update hugging face space on push

---

cog.yaml
integrations/README.md
integrations/cog_riffusion.py
pyproject.toml
riffusion/riffusion_pipeline.py

Support hosting on Replicate using the cog interface.
Continuation of: https://github.com/riffusion/riffusion/pull/26
Topic: cog_integration

Cog integration

---

riffusion/streamlit/pages/audio_to_audio.py
riffusion/streamlit/pages/image_to_audio.py
riffusion/streamlit/pages/sample_clips.py
riffusion/streamlit/pages/split_audio.py
riffusion/streamlit/pages/text_to_audio.py
riffusion/streamlit/pages/text_to_audio_batch.py

Help text for app

---

riffusion/streamlit/pages/audio_to_audio.py
riffusion/streamlit/pages/split_audio.py

Add an option in the splitter to recombine stems at the end.
Topic: recombine_audio

Recombine audio

---

riffusion/streamlit/pages/text_to_audio.py

Topic: text_to_audio_multiple_riffs

Text to audio supports multiple clips

---

requirements.txt

Closes: #76
Topic: pip_pysoundfile

Add pysoundfile to requirements

---

riffusion/streamlit/pages/sample_clips.py

Topic: sample_clips_save_images

Sample clips can save images

---

riffusion/streamlit/util.py

This should avoid the most basic conflict with multiple users on
the app at one time. Seems to work with initial testing.
Topic: pipeline_lock
Closes: #73

Lock to prevent concurrent access to model pipeline in playground

---

riffusion/streamlit/pages/audio_to_audio.py
riffusion/streamlit/util.py

Allows for better preserving structure with audio to audio.
Topic: magic_mix

[Playground] Add magic mix to audio2audio

---

riffusion/streamlit/pages/interpolation.py

Topic: interpolation_defaults
Reviewer: sethforsgren

[Playground] Change interpolation defaults

---

riffusion/streamlit/pages/audio_to_audio.py
riffusion/streamlit/pages/interpolation.py
riffusion/streamlit/pages/text_to_audio.py
riffusion/streamlit/util.py

[Playground] Tune parameters

---

integrations/README.md

@hmartiro I've updated the integrations README to better explain the process for pushing a model to Replicate. We also internally moved the model to be linked to your `Riffusion` org on github, so I've updated the links here to reflect that. Lmk if you have any concerns there. 
We'd love to feature Riffusion in a tweet from our account! Are you on board with that?

updating cog readme

---

dev_requirements.txt
riffusion/cli.py

Add audio_to_image_batch and sample_clips_batch

---

riffusion/streamlit/pages/text_to_audio.py
riffusion/streamlit/util.py

Also have a toggle for 20khz spectrogram mode
Topic: playground_custom_checkpoints_text_to_audio

Support custom checkpoints in text_to_audio

---

riffusion/py.typed
setup.py

Allows mypy to type check when used in other packages via PEP 561.

Add py.typed for mypy use

---

riffusion/streamlit/tasks/audio_to_audio.py
riffusion/streamlit/tasks/interpolation.py
riffusion/streamlit/tasks/text_to_audio.py
riffusion/streamlit/tasks/text_to_audio_batch.py
riffusion/streamlit/util.py

Topic: batch_text_with_multiple_models

Streamlit fixes and batch text to audio with multiple models
